language: python
python:
  - "3.7"  # 3.6 development branch
env:
- DJANGO_VERSION=1.11.2
# install dependencies
install:
- pip install -r helplineApp/requirements.txt

# run test scripts
script:
- python helplineApp/manage.py migrate
- python helplineApp/manage.py makemigrations
- python helplineApp/manage.py test 
