language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
env:
- DJANGO_VERSION=1.11.2
- DJANGO_SETTINGS_MODULE='helplineApp.settings.development'
# install dependencies
install:
- pip install -r requirements.txt

# run test scripts
script:
- python src/manage.py test 
