version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r helplineApp/requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run: 
          name: Running tests
          command: |
            . venv/bin/activate
            python3 helplineApp/manage.py test
          command: |
            export AFRICAS_TALKING_USERNAME = sandbox
            export AFRICAS_TALKING_API_KEY=“4d7fe2e79fb7871d5c5e24fdc051088ebb74ec6ed5613b44d2749c61a5cb8078"
            export LAST_RECEIVED=0
      - store_artifacts:
          path: test-reports/
          destination: python_app